### ISSUE TITLE
[BUG] Task ScrollView not longer enough

### ISSUE THREAD

**Issue by mbachircherif** [worldline/RunningOrder#96] opened 2021-06-02 15:46 UTC
**Describe the bug**
The scrollview which display task previews cut the last one because not longer enough.

**To Reproduce**
Came randomly when I added a new task.

**Expected behavior**
Need to see all the task preview. 

**Screenshots**
<img width="1438" alt="Capture d’écran 2021-06-02 à 17 38 23" src="https://user-images.githubusercontent.com/23616188/120511159-6cbbf700-c3ca-11eb-965e-d8b1b3137860.png">

**Additional context**
Once the application restarts, the problem is solved.

**Comment by zarghol** [comment] 2021-07-13 08:14
We can't reproduce the bug, and @mbachircherif didn't reproduce it either in 1 month so I will close this bug. We'll reopen it if it appears again.

**Closed as completed by zarghol** 2021-07-13 08:14 UTC
Labels: bug
